// Originally generated by the Supabase tooling, then edited on purpose: the generated version
// hardcodes a project URL and anon key as fallbacks. If you regenerate this file, re-apply the
// change below - a committed fallback points every clone of this repo at one person's project.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  throw new Error(
    'SUPABASE_URL and SUPABASE_ANON_KEY must be set. Copy .env.example to .env and fill in your ' +
    'own project values - see the README. There is deliberately no fallback project here.'
  );
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);